version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: smartworkout
      POSTGRES_USER: smartworkout
      POSTGRES_PASSWORD: supersecretpassword1123
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "69420:8080"
